import { spawnSync } from "node:child_process";
import { rmSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const isWindows = process.platform === "win32";
const nodeCommand = process.execPath;

const smoothnessQcPresets = {
  quick: {
    COPC_SMOOTHNESS_SAMPLES: "autzen-classified",
    COPC_SMOOTHNESS_POINT_BUDGETS: "20000",
    COPC_SMOOTHNESS_POINT_COUNT: "180000",
    COPC_SMOOTHNESS_REPEATS: "1",
    COPC_SMOOTHNESS_DURATION_MS: "1200",
    COPC_SMOOTHNESS_CAMERA_STEPS: "12",
    COPC_SMOOTHNESS_MIN_SELECTED_DEPTH: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_AVG_FPS: "30",
    COPC_SMOOTHNESS_ASSERT_MAX_P95_FRAME_MS: "67",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAME_MS: "100",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAMES_OVER_50: "10",
    COPC_SMOOTHNESS_ASSERT_MAX_STREAM_TOTAL_MS: "250",
    COPC_SMOOTHNESS_ASSERT_MAX_FIRST_RESPONSE_MS: "250",
    COPC_SMOOTHNESS_ASSERT_MAX_FINAL_DETAIL_MS: "1500",
    COPC_SMOOTHNESS_ASSERT_MAX_MEASURED_DURATION_OVER_MS: "2000",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_POINTS: "10000",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_NODE_COVERAGE_RATIO: "1",
  },
  contest: {
    COPC_SMOOTHNESS_SAMPLES: "autzen-classified,millsite-reservoir",
    COPC_SMOOTHNESS_POINT_BUDGETS: "20000",
    COPC_SMOOTHNESS_POINT_COUNT: "180000",
    COPC_SMOOTHNESS_REPEATS: "1",
    COPC_SMOOTHNESS_DURATION_MS: "1200",
    COPC_SMOOTHNESS_CAMERA_STEPS: "12",
    COPC_SMOOTHNESS_MIN_SELECTED_DEPTH: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_AVG_FPS: "30",
    COPC_SMOOTHNESS_ASSERT_MAX_P95_FRAME_MS: "67",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAME_MS: "100",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAMES_OVER_50: "10",
    COPC_SMOOTHNESS_ASSERT_MAX_STREAM_TOTAL_MS: "250",
    COPC_SMOOTHNESS_ASSERT_MAX_FIRST_RESPONSE_MS: "250",
    COPC_SMOOTHNESS_ASSERT_MAX_FINAL_DETAIL_MS: "8000",
    COPC_SMOOTHNESS_ASSERT_MAX_MEASURED_DURATION_OVER_MS: "2500",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_POINTS: "10000",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_NODE_COVERAGE_RATIO: "1",
  },
  cacheReset: {
    COPC_SMOOTHNESS_SAMPLES: "millsite-reservoir",
    COPC_SMOOTHNESS_POINT_BUDGETS: "10000",
    COPC_SMOOTHNESS_POINT_COUNT: "180000",
    COPC_SMOOTHNESS_REPEATS: "1",
    COPC_SMOOTHNESS_DURATION_MS: "1200",
    COPC_SMOOTHNESS_CAMERA_STEPS: "12",
    COPC_SMOOTHNESS_MIN_SELECTED_DEPTH: "1",
    COPC_SMOOTHNESS_CLEAR_CACHES_BEFORE_RUN: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_AVG_FPS: "20",
    COPC_SMOOTHNESS_ASSERT_MAX_P95_FRAME_MS: "100",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAME_MS: "200",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAMES_OVER_50: "20",
    COPC_SMOOTHNESS_ASSERT_MAX_STREAM_TOTAL_MS: "3000",
    COPC_SMOOTHNESS_ASSERT_MAX_FIRST_RESPONSE_MS: "1000",
    COPC_SMOOTHNESS_ASSERT_MAX_FINAL_DETAIL_MS: "5000",
    COPC_SMOOTHNESS_ASSERT_MAX_MEASURED_DURATION_OVER_MS: "5000",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_POINTS: "5000",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_NODE_COVERAGE_RATIO: "1",
  },
  coldReset: {
    COPC_SMOOTHNESS_SAMPLES: "millsite-reservoir",
    COPC_SMOOTHNESS_POINT_BUDGETS: "10000",
    COPC_SMOOTHNESS_POINT_COUNT: "10000",
    COPC_SMOOTHNESS_REPEATS: "1",
    COPC_SMOOTHNESS_DURATION_MS: "1200",
    COPC_SMOOTHNESS_CAMERA_STEPS: "12",
    COPC_SMOOTHNESS_MIN_SELECTED_DEPTH: "2",
    COPC_SMOOTHNESS_CACHE_RESET_MODE: "layer",
    COPC_SMOOTHNESS_WAIT_FOR_FINAL_DETAIL: "0",
    COPC_SMOOTHNESS_ASSERT_MIN_AVG_FPS: "15",
    COPC_SMOOTHNESS_ASSERT_MAX_P95_FRAME_MS: "150",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAME_MS: "500",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAMES_OVER_50: "30",
    COPC_SMOOTHNESS_ASSERT_MAX_STREAM_TOTAL_MS: "10000",
    COPC_SMOOTHNESS_ASSERT_MAX_FIRST_RESPONSE_MS: "3000",
    COPC_SMOOTHNESS_ASSERT_MAX_MEASURED_DURATION_OVER_MS: "12000",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_POINTS: "5000",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_NODE_COVERAGE_RATIO: "0",
  },
  coldDetail: {
    COPC_SMOOTHNESS_SAMPLES: "millsite-reservoir",
    COPC_SMOOTHNESS_POINT_BUDGETS: "360000",
    COPC_SMOOTHNESS_POINT_COUNT: "360000",
    COPC_SMOOTHNESS_REPEATS: "1",
    COPC_SMOOTHNESS_WARMUP_RUNS: "0",
    COPC_SMOOTHNESS_DURATION_MS: "1200",
    COPC_SMOOTHNESS_CAMERA_STEPS: "12",
    COPC_SMOOTHNESS_MOVE_METERS: "10",
    COPC_SMOOTHNESS_CAMERA_HEIGHT_METERS: "550",
    COPC_SMOOTHNESS_MIN_SELECTED_DEPTH: "4",
    COPC_SMOOTHNESS_CACHE_RESET_MODE: "layer",
    COPC_SMOOTHNESS_WAIT_FOR_FINAL_DETAIL: "1",
    COPC_SMOOTHNESS_PREFETCH_WAIT_TIMEOUT_MS: "30000",
    COPC_SMOOTHNESS_ASSERT_MIN_AVG_FPS: "30",
    COPC_SMOOTHNESS_ASSERT_MAX_P95_FRAME_MS: "67",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAME_MS: "150",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAMES_OVER_50: "10",
    COPC_SMOOTHNESS_ASSERT_MAX_STREAM_TOTAL_MS: "15000",
    COPC_SMOOTHNESS_ASSERT_MAX_FIRST_RESPONSE_MS: "1000",
    COPC_SMOOTHNESS_ASSERT_MAX_FINAL_DETAIL_MS: "15000",
    COPC_SMOOTHNESS_ASSERT_MAX_MEASURED_DURATION_OVER_MS: "2000",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_POINTS: "50000",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_NODE_COVERAGE_RATIO: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_WEIGHTED_NODE_COVERAGE_RATIO: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_FINAL_NODES: "24",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_FINAL_NODES: "23",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_POINTS_PER_FINAL_NODE: "1800",
    COPC_SMOOTHNESS_ASSERT_REQUIRE_GEOMETRY_TIMING: "1",
    COPC_SMOOTHNESS_ASSERT_REQUIRE_PREFETCH: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_PREFETCH_REQUESTED_NODES: "16",
    COPC_SMOOTHNESS_ASSERT_REQUIRE_POST_PREFETCH_REFINEMENT: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_POST_PREFETCH_SELECTED_DEPTH: "5",
    COPC_SMOOTHNESS_ASSERT_MIN_POST_PREFETCH_RENDERED_POINTS: "300000",
    COPC_SMOOTHNESS_ASSERT_MAX_GEOMETRY_ROUNDTRIP_MS: "6000",
    COPC_SMOOTHNESS_ASSERT_MAX_GEOMETRY_DECODE_MS: "5000",
    COPC_SMOOTHNESS_ASSERT_MAX_GEOMETRY_WORKER_MS: "5000",
    COPC_SMOOTHNESS_ASSERT_MAX_GEOMETRY_QUEUE_MS: "2000",
    COPC_SMOOTHNESS_ASSERT_MAX_AVG_GEOMETRY_QUEUE_MS: "500",
  },
  zoomDetail: {
    COPC_SMOOTHNESS_SAMPLES: "millsite-reservoir",
    COPC_SMOOTHNESS_POINT_BUDGETS: "360000",
    COPC_SMOOTHNESS_POINT_COUNT: "360000",
    COPC_SMOOTHNESS_REPEATS: "1",
    COPC_SMOOTHNESS_DURATION_MS: "1200",
    COPC_SMOOTHNESS_CAMERA_STEPS: "12",
    COPC_SMOOTHNESS_MOVE_METERS: "10",
    COPC_SMOOTHNESS_CAMERA_HEIGHT_METERS: "550",
    COPC_SMOOTHNESS_MIN_SELECTED_DEPTH: "4",
    COPC_SMOOTHNESS_CACHE_RESET_MODE: "layer",
    COPC_SMOOTHNESS_WAIT_FOR_FINAL_DETAIL: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_AVG_FPS: "15",
    COPC_SMOOTHNESS_ASSERT_MAX_P95_FRAME_MS: "150",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAME_MS: "500",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAMES_OVER_50: "35",
    COPC_SMOOTHNESS_ASSERT_MAX_STREAM_TOTAL_MS: "20000",
    COPC_SMOOTHNESS_ASSERT_MAX_FIRST_RESPONSE_MS: "3000",
    COPC_SMOOTHNESS_ASSERT_MAX_FINAL_DETAIL_MS: "20000",
    COPC_SMOOTHNESS_ASSERT_MAX_MEASURED_DURATION_OVER_MS: "22000",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_POINTS: "50000",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_NODE_COVERAGE_RATIO: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_WEIGHTED_NODE_COVERAGE_RATIO: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_FINAL_NODES: "24",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_FINAL_NODES: "23",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_POINTS_PER_FINAL_NODE: "1800",
    COPC_SMOOTHNESS_ASSERT_REQUIRE_GEOMETRY_TIMING: "1",
    COPC_SMOOTHNESS_ASSERT_REQUIRE_PREFETCH: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_PREFETCH_REQUESTED_NODES: "16",
    COPC_SMOOTHNESS_ASSERT_MAX_GEOMETRY_ROUNDTRIP_MS: "22000",
    COPC_SMOOTHNESS_ASSERT_MAX_GEOMETRY_DECODE_MS: "15000",
    COPC_SMOOTHNESS_ASSERT_MAX_GEOMETRY_WORKER_MS: "15000",
    COPC_SMOOTHNESS_ASSERT_MAX_GEOMETRY_QUEUE_MS: "22000",
    COPC_SMOOTHNESS_ASSERT_MAX_AVG_GEOMETRY_QUEUE_MS: "10000",
  },
  warmZoomDetail: {
    COPC_SMOOTHNESS_SAMPLES: "millsite-reservoir",
    COPC_SMOOTHNESS_POINT_BUDGETS: "360000",
    COPC_SMOOTHNESS_POINT_COUNT: "360000",
    COPC_SMOOTHNESS_REPEATS: "2",
    COPC_SMOOTHNESS_WARMUP_RUNS: "1",
    COPC_SMOOTHNESS_WARMUP_SETTLE_TIMEOUT_MS: "30000",
    COPC_SMOOTHNESS_DURATION_MS: "1200",
    COPC_SMOOTHNESS_CAMERA_STEPS: "12",
    COPC_SMOOTHNESS_MOVE_METERS: "10",
    COPC_SMOOTHNESS_CAMERA_HEIGHT_METERS: "550",
    COPC_SMOOTHNESS_MIN_SELECTED_DEPTH: "4",
    COPC_SMOOTHNESS_CACHE_RESET_MODE: "none",
    COPC_SMOOTHNESS_WAIT_FOR_FINAL_DETAIL: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_AVG_FPS: "30",
    COPC_SMOOTHNESS_ASSERT_MAX_P95_FRAME_MS: "67",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAME_MS: "150",
    COPC_SMOOTHNESS_ASSERT_MAX_FRAMES_OVER_50: "10",
    COPC_SMOOTHNESS_ASSERT_MAX_STREAM_TOTAL_MS: "8000",
    COPC_SMOOTHNESS_ASSERT_MAX_FIRST_RESPONSE_MS: "250",
    COPC_SMOOTHNESS_ASSERT_MAX_FINAL_DETAIL_MS: "8000",
    COPC_SMOOTHNESS_ASSERT_MAX_MEASURED_DURATION_OVER_MS: "2000",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_POINTS: "150000",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_NODE_COVERAGE_RATIO: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_WEIGHTED_NODE_COVERAGE_RATIO: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_FINAL_NODES: "24",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_FINAL_NODES: "23",
    COPC_SMOOTHNESS_ASSERT_MIN_RENDERED_POINTS_PER_FINAL_NODE: "2500",
    COPC_SMOOTHNESS_ASSERT_REQUIRE_GEOMETRY_TIMING: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_GEOMETRY_CACHE_HITS: "1",
    COPC_SMOOTHNESS_ASSERT_REQUIRE_PREFETCH: "1",
    COPC_SMOOTHNESS_ASSERT_MIN_PREFETCH_REQUESTED_NODES: "16",
    COPC_SMOOTHNESS_ASSERT_MAX_GEOMETRY_ROUNDTRIP_MS: "5000",
    COPC_SMOOTHNESS_ASSERT_MAX_GEOMETRY_DECODE_MS: "4000",
    COPC_SMOOTHNESS_ASSERT_MAX_GEOMETRY_WORKER_MS: "4000",
    COPC_SMOOTHNESS_ASSERT_MAX_GEOMETRY_QUEUE_MS: "2000",
    COPC_SMOOTHNESS_ASSERT_MAX_AVG_GEOMETRY_QUEUE_MS: "500",
  },
};
const presetName = readPresetName();
const presetDefaults = smoothnessQcPresets[presetName];
const artifactStem = `smoothness-${toKebabCase(presetName)}`;
const benchmarkOutputName = `${artifactStem}.json`;
const benchmarkOutputPath = path.join(
  repoRoot,
  "output",
  "smoothness-benchmark",
  benchmarkOutputName,
);
const assertionOutputPath = path.join(
  repoRoot,
  "output",
  "smoothness-benchmark",
  `${artifactStem}-assertion.json`,
);
const env = {
  ...presetDefaults,
  ...process.env,
  COPC_SMOOTHNESS_QC_PRESET: toKebabCase(presetName),
  COPC_SMOOTHNESS_OUTPUT_NAME: benchmarkOutputName,
};

console.log(`Running ${presetName} camera-stream smoothness QC...`);
rmSync(benchmarkOutputPath, { force: true });
rmSync(assertionOutputPath, { force: true });
runNodeScript("scripts/benchmark-smoothness.mjs");
runNodeScript("scripts/assert-smoothness-benchmark.mjs", [
  "--input",
  benchmarkOutputPath,
  "--output",
  assertionOutputPath,
]);

function toKebabCase(value) {
  return value.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function readPresetName() {
  const presetName =
    readPresetArg() ?? process.env.COPC_SMOOTHNESS_QC_PRESET ?? "quick";

  if (!(presetName in smoothnessQcPresets)) {
    throw new Error(
      `Unknown smoothness QC preset "${presetName}". Expected one of: ${Object.keys(
        smoothnessQcPresets,
      ).join(", ")}.`,
    );
  }

  return presetName;
}

function readPresetArg() {
  const presetArg = process.argv.find((arg) => arg.startsWith("--preset="));

  if (presetArg) {
    return presetArg.slice("--preset=".length);
  }

  if (process.argv.includes("--quick")) {
    return "quick";
  }

  if (process.argv.includes("--contest")) {
    return "contest";
  }

  if (process.argv.includes("--cache-reset")) {
    return "cacheReset";
  }

  if (process.argv.includes("--cold-reset")) {
    return "coldReset";
  }

  if (process.argv.includes("--cold-detail")) {
    return "coldDetail";
  }

  if (process.argv.includes("--zoom-detail")) {
    return "zoomDetail";
  }

  if (process.argv.includes("--warm-zoom-detail")) {
    return "warmZoomDetail";
  }

  return undefined;
}

function runNodeScript(scriptPath, args = []) {
  const result = spawnSync(nodeCommand, [scriptPath, ...args], {
    cwd: repoRoot,
    env,
    shell: isWindows,
    stdio: "inherit",
  });

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    throw new Error(`${scriptPath} failed with exit code ${result.status}`);
  }
}
